# Generated by Django 4.1.5 on 2023-01-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillBoard',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('rank', models.IntegerField()),
                ('song', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('last_week', models.IntegerField()),
                ('peak_rank', models.IntegerField()),
                ('weeks_on_board', models.IntegerField()),
            ],
        ),
    ]
